spring.application.name=aleap

server.port=8084


spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://51.222.155.92:3306/murthy_workflow
spring.datasource.username=aleap_user
spring.datasource.password=Aleap@12345

#pCyIJv5JV2MGCKBm  RrigKwgPmNurrIYC

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# create and drop table, good for testing, production set to none or comment it
spring.jpa.hibernate.ddl-auto=update

server.servlet.context-path=/workflow

# SpringDoc OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.use-root-path=false
springdoc.show-actuator=false
springdoc.api-docs.enabled=true
springdoc.default-flat-param-object=false
springdoc.remove-broken-reference-definitions=true
spring.security.enabled=true
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000


#file storage properties
spring.servlet.multipart.max-file-size=1024KB
spring.servlet.multipart.max-request-size=1024KB
#storage.file.directory.location=C:/Users/Chait/Desktop/Ramp1/

#storage.file.directory.location=/home/metaverseedu/public_html/workflowfiles-temp/

#DEV ENV
storage.file.directory.location=/home/ubuntu/aleap-files/

#PROD ENV
#storage.file.directory.location=/home/metaverseedu/public_html/workflowfiles/