package com.metaverse.workflow.questionnaire.service;

import com.metaverse.workflow.model.QuestionnaireForm;

public class QuestionnaireFormMapper {

    public static QuestionnaireForm mapToQuestionnaireForm(QuestionnaireFormRequest req) {
        return QuestionnaireForm.builder()
                .name(req.getName())
                .fatherOrHusbandName(req.getFatherOrHusbandName())
                .dateOfBirth(req.getDateOfBirth())
                .age(req.getAge())
                .qualification(req.getQualification())
                .emailId(req.getEmailId())
                .phoneNo(req.getPhoneNo())
                .alternatePhoneNo(req.getAlternatePhoneNo())
                .gender(req.getGender())
                .caste(req.getCaste())
                .disability(req.getDisability())
                .doorNo(req.getDoorNo())
                .streetName(req.getStreetName())
                .village(req.getVillage())
                .panchayatName(req.getPanchayatName())
                .mandal(req.getMandal())
                .district(req.getDistrict())
                .state(req.getState())
                .pincode(req.getPincode())
                .aadharNo(req.getAadharNo())
                .panCard(req.getPanCard())
                .shgName(req.getShgName())
                .yearsSpentInShg(req.getYearsSpentInShg())
                .shgLeaderName(req.getShgLeaderName())
                .positionInShg(req.getPositionInShg())
                .mandalFederationName(req.getMandalFederationName())
                .voName(req.getVoName())
                .sourceOfIncome(req.getSourceOfIncome())
                .skills(req.getSkills())
                .willingToStartBusiness(req.getWillingToStartBusiness())
                .businessType(req.getBusinessType())
                .availableForTraining(req.getAvailableForTraining())
                .willingToWorkWithMsme(req.getWillingToWorkWithMsme())
                .govtSchemes(req.getGovtSchemes())
                .digitalPlatforms(req.getDigitalPlatforms())
                .certifications(req.getCertifications())
                .financialLinkages(req.getFinancialLinkages())
                .build();
    }

    public static QuestionnaireFormResponse mapToQuestionnaireResponse(QuestionnaireForm entity) {
        return QuestionnaireFormResponse.builder()
                .id(entity.getId())
                .name(entity.getName())
                .fatherOrHusbandName(entity.getFatherOrHusbandName())
                .dateOfBirth(entity.getDateOfBirth())
                .age(entity.getAge())
                .qualification(entity.getQualification())
                .emailId(entity.getEmailId())
                .phoneNo(entity.getPhoneNo())
                .alternatePhoneNo(entity.getAlternatePhoneNo())
                .gender(entity.getGender())
                .caste(entity.getCaste())
                .disability(entity.getDisability())
                .doorNo(entity.getDoorNo())
                .streetName(entity.getStreetName())
                .village(entity.getVillage())
                .panchayatName(entity.getPanchayatName())
                .mandal(entity.getMandal())
                .district(entity.getDistrict())
                .state(entity.getState())
                .pincode(entity.getPincode())
                .aadharNo(entity.getAadharNo())
                .panCard(entity.getPanCard())
                .shgName(entity.getShgName())
                .yearsSpentInShg(entity.getYearsSpentInShg())
                .shgLeaderName(entity.getShgLeaderName())
                .positionInShg(entity.getPositionInShg())
                .mandalFederationName(entity.getMandalFederationName())
                .voName(entity.getVoName())
                .sourceOfIncome(entity.getSourceOfIncome())
                .skills(entity.getSkills())
                .willingToStartBusiness(entity.getWillingToStartBusiness())
                .businessType(entity.getBusinessType())
                .availableForTraining(entity.getAvailableForTraining())
                .willingToWorkWithMsme(entity.getWillingToWorkWithMsme())
                .govtSchemes(entity.getGovtSchemes())
                .digitalPlatforms(entity.getDigitalPlatforms())
                .certifications(entity.getCertifications())
                .financialLinkages(entity.getFinancialLinkages())
                .build();
    }
}
